# Generated by Django 4.1.4 on 2022-12-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': '-time_stamp'},
        ),
    ]
