# Generated by Django 4.1.4 on 2022-12-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'time_stamp'},
        ),
    ]
