# Generated by Django 4.1.4 on 2022-12-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
