# Generated by Django 4.1.4 on 2022-12-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0005_alter_task_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
